### PR TITLE
bump up to ibc-go/v2

### PR DESCRIPTION
**Pull request by nghuyenthevinh2000**
On request of:
https://github.com/CosmosContracts/bounties/issues/13#issuecomment-1030706922

Closes: #202 

## Implementation details
Upgrade ibc v1.1.5 to ibc/v2 v2.0.2

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

### CODE REVIEW

**Comment by JakeHartnell** [comment]
Are there any plans to use a more recent IBC-go version? Would be really nice for Juno smart contracts that want to integrate.

**Comment by nghuyenthevinh2000** [comment]
@JakeHartnell 
are you mentioning IBCv3? sure, I will upgrade it to IBCv3

**Comment by JakeHartnell** [comment]
> are you mentioning IBCv3? sure, I will upgrade it to IBCv3

My question is for Band Protocol, the maintainers of this repo. IBCv2 would be sufficient.

**Comment by taobun** [comment]
We are considering on upgrade IBC from v1 to v2. This upgrade is a consensus breaking change, so we need to find a timeline and plan how to support other client when chain need to be stop when upgrade.

**Comment by Miniminitrue** [comment]
+1 IBC upgrade is key to anchor BAND in the Cosmos space.

**Comment by taobun** [comment]
Already patch on #212

**Pull request closed without merging**
